services:
  skedio-db-dev:
    image: mysql:latest
    container_name: skedio-db-dev
    networks:
      - skedio-dev
    ports:
      - "3306:3306"
    volumes:
      - ./migration/focuz-migration/flyway/mysql/init:/docker-entrypoint-initdb.d
      - ./database/mysql/dev/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      TZ: Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123" ]
      interval: 5s
      retries: 3
      timeout: 10s

  skedio-cache-dev:
    image: redis:latest
    container_name: skedio-cache-dev
    networks:
      - skeio-dev
    volumes:
      - ./infrastructure/cache/redis/dev/data:/data
      - ./infrastructure/cache/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 3
      timeout: 10s


  skedio-mongo-dev:
    image: mongo:latest
    container_name: skedio-mongo-dev
    networks:
      - focuz-dev
    volumes:
      - ./infrastructure/database/mongo/dev/data:/data/db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: skedio
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: auth
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--username",
        "focuz",
        "--password",
        "123",
        "--authenticationDatabase",
        "admin",
        "--eval",
        "db.adminCommand('ping').ok"
      ]
      interval: 5s
      retries: 3
      timeout: 10s

  skedio-rabbitmq-dev:
    image: rabbitmq:4-management
    container_name: skedio-rabbitmq-dev
    networks:
      - skedio-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
       RABBITMQ_DEFAULT_USER: skedio
       RABBITMQ_DEFAULT_PASS: 123
    volumes:
      - ./infrastructure/database/rabbitmq/dev/data:/var/lib/rabbitmq

  administration-flyway-dev:
    image: flyway/flyway:latest
    container_name: administration-migration-dev
    networks:
      - skedio-dev
    command:
      - "-url=jdbc:mysql://skedio-db-dev:3306/administration?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
      - "-user=root"
      - "-password=123"
      - "migrate"
    volumes:
      - ./migration/skedio-migration/flyway/mysql/administration:/flyway/sql
    depends_on:
      focuz-db-dev:
          condition: service_healthy

  auth-flyway-dev:
    image: flyway/flyway:latest
    container_name: auth-flyway-dev
    networks:
      - skedio-dev
    command:
      - "-url=jdbc:mysql://skedio-db-dev:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
      - "-user=root"
      - "-password=123"
      - "migrate"
    volumes:
      - ./migration/skedio-migration/flyway/mysql/auth:/flyway/sql
    depends_on:
      focuz-db-dev:
        condition: service_healthy

  discovery-dev:
    build:
      context: ./platform-services/discovery-service/.
    container_name: discovery-dev
    networks:
      - skedio-dev
    ports:
      - "8761:8761"

  gateway-dev:
    build:
      context: ./platform-services/gateway/.
    container_name: gateway-dev
    networks:
      - skedio-dev
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - discovery-dev

#  administration-dev:
#    build:
#      context: ./business-services/administration-service/.
#    container_name: administration-dev
#    networks:
#      - skedio-dev
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#    depends_on:
#      focuz-db-dev:
#        condition: service_healthy
#      focuz-cache-dev:
#        condition: service_healthy
#      discovery-dev:
#        condition: service_started

#  auth-dev:
#    build:
#      context: ./business-services/auth-service/.
#    container_name: auth-dev
#    networks:
#      - skedio-dev
#    ports:
#      - "8083:8081"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#    depends_on:
#      focuz-db-dev:
#        condition: service_healthy
#      focuz-cache-dev:
#        condition: service_healthy
#      focuz-mongo-dev:
#        condition: service_healthy
#      discovery-dev:
#        condition: service_started

volumes:
  skedio-mysql:

networks:
  skedio-dev:
      external: true