spring:
  application:
    name: administration-service
  datasource:
    url: jdbc:mysql://localhost:3307/administration
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

core:
  permitAll: /**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
