spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: administration-service
#              uri: lb://ADMINISTRATION-SERVICE
#              predicates:
#                - Path=/api/administration-service/**
#              filters:
#                - RewritePath=/api/administration-service/(?<segment>.*),/${segment}
#            - id: auth-service
#              uri: lb://AUTH-SERVICE
#              predicates:
#                - Path=/api/auth-service/**
#              filters:
#                - RewritePath=/api/auth-service/(?<segment>.*),/${segment}
  application:
    name: gateway


eureka:
  client:
    service-url:
      defaultZone: http://discovery-dev:8761/eureka
      
server:
  port: 8082